### ISSUE TITLE
DSI_Studio docker build failing 

### ISSUE THREAD

**Issue by maksteel** [frankyeh/TIPL#8]
```
root@9d938e80a34e:/dsistudio/build# qmake ../src && make
g++ -c -pipe -fpermissive -w -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../src -I. -I./plot -I../src/libs -I../src/libs/dsi -I../src/libs/tracking -I../src/libs/mapping -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o RegionModel.o ../src/tracking/region/RegionModel.cpp
In file included from ../src/tipl/tipl.hpp:85,
                 from ../src/tracking/region/RegionModel.h:7,
                 from ../src/tracking/region/RegionModel.cpp:6:
../src/tipl/vis/march_cube.hpp: In instantiation of 'tipl::march_cube<VectorType>::march_cube(const ImageType&, double) [with ImageType = tipl::image<unsigned char, 3>; VectorType = tipl::vector<3>]':
../src/tracking/region/RegionModel.cpp:101:73:   required from here
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<unsigned char, 3>::value_type' {aka 'unsigned char'}, which is is not a class type
  443 |             std::vector<typename ImageType::value_type> pixels;
      |                                                         ^~~~~~
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<unsigned char, 3>::value_type' {aka 'unsigned char'}, which is is not a class type
../src/tipl/vis/march_cube.hpp: In instantiation of 'tipl::march_cube<VectorType>::march_cube(const ImageType&, double) [with ImageType = tipl::image<float, 3>; VectorType = tipl::vector<3>]':
../src/tracking/region/RegionModel.cpp:154:27:   required from here
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<float, 3>::value_type' {aka 'float'}, which is is not a class type
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<float, 3>::value_type' {aka 'float'}, which is is not a class type
make: *** [Makefile:3178: RegionModel.o] Error 1
root@9d938e80a34e:/dsistudio/build# 
```

**Comment by frankyeh** [comment]
Please update TIPL from github to see if it works.
Frank

**Comment by maksteel** [comment]
Updated docker image, that now builds on Ubuntu 18.04, the above issue is resolved. https://github.com/maksteel/dsi-studio-docker/commit/d5e3d591ae25dac15372534b3cb936b242567bc8

**Comment by frankyeh** [comment]
Thanks for the update.
Frank
